apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jvdqo9due-nodejs 
  janus-idp.io/tekton: jvdqo9due-nodejs
  backstage.io/kubernetes-id: jvdqo9due-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jvdqo9due-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml