apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jvdqo9due-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvdqo9due-nodejs 
  name: jvdqo9due-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jvdqo9due-nodejs 
